"""empty message

Revision ID: 12208f2843b9
Revises: 3cbc1807801b
Create Date: 2018-06-22 17:19:57.246000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12208f2843b9'
down_revision = '3cbc1807801b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='courses')
    op.create_unique_constraint(None, 'courses', ['subjNum'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='unique')
    op.create_index('title', 'courses', ['title'], unique=True)
    # ### end Alembic commands ###
