"""empty message

Revision ID: 3cbc1807801b
Revises: ea0d6188f4f1
Create Date: 2018-06-22 17:18:15.806000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbc1807801b'
down_revision = 'ea0d6188f4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('subjNum', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'subjNum')
    # ### end Alembic commands ###
