"""empty message

Revision ID: 593af53038d1
Revises: 
Create Date: 2018-05-03 14:17:34.399967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593af53038d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('number', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('term', sa.String(length=256), nullable=True),
    sa.Column('creditsMax', sa.Integer(), nullable=True),
    sa.Column('creditsMin', sa.Integer(), nullable=True),
    sa.Column('prereqs', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
