"""empty message

Revision ID: ea0d6188f4f1
Revises: 5a64a42a9600
Create Date: 2018-06-13 19:30:42.078000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea0d6188f4f1'
down_revision = '5a64a42a9600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='copy')
    op.drop_table('copy')
    op.add_column('courses', sa.Column('acadGroup', sa.String(length=10), nullable=True))
    op.drop_index('courseNum', table_name='courses')
    op.drop_index('courseTerm', table_name='courses')
    op.drop_index('testing', table_name='courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('testing', 'courses', ['subject'], unique=False)
    op.create_index('courseTerm', 'courses', ['term'], unique=False)
    op.create_index('courseNum', 'courses', ['number'], unique=False)
    op.drop_column('courses', 'acadGroup')
    op.create_table('copy',
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('number', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('term', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('creditsMax', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('creditsMin', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('prereqs', mysql.TEXT(), nullable=True),
    sa.Column('distribution', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('gradingType', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_index('title', 'copy', ['title'], unique=True)
    # ### end Alembic commands ###
